### ISSUE TITLE
Messages appear to be resent twice when an emoji is attached

### ISSUE THREAD

**Issue by GJKrupa** [daniel-sc/rocketchat-modern-client#11]
I've implemented a bot with slash commands using the library but found that when someone attached an emoji to one of the command messages, the command then executed twice more. There appears to be no data in the ChatMessage class to indicate if the message was a new one, an edit or the attachment of an emoji.

**Comment by daniel-sc** [comment]
Hi @GJKrupa,
this should be resolved with v0.1.2 - thanks for your contribution!
