### ISSUE TITLE
How to listen for events of any kind using WSClient onMessage

### ISSUE THREAD

**Issue by thetuyo** [daniel-sc/rocketchat-modern-client#23]
I'm using rocket.chat.realtime.api.rxjs for our front end.   Now trying to listen on the backend using this for any event coming back from the RC server.   Like when a user's room is created, deleted etc is there a way to do that now or can I just listen.  

Is there a way to do this doing something like  client.onMessage()  ?

thanks!

**Comment by daniel-sc** [comment]
Hi @thetuyo 
currently this is not possible - the raw messages are not exposed.
A PR for this would of course be very welcome!

Best, Daniel

**Comment by thetuyo** [comment]
This is helpful, many thanks!

**Comment by thetuyo** [comment]
However another issue is I can't listen to room events easily because you're not populating the Subscription.java object with everything about a room.   There is only rid, _id ... nothing about last message , so this example will only give you basic rooms not LiveChat rooms.

```
try(RocketChatClient client = new RocketChatClient(URL, new LoginParam(USERNAME, PASSWORD))) {
    Observable<ChatMessage> msgStream = client.streamRoomMessages(roomId).join();
    msgStream.forEach(msg -> System.out.println("received msg: " + msg));
    // block thread until you got enough messages.. (or don't use try-with and close client explicitly)
    msgStream.dispose();
}
```

I need to be able to listen to LiveChat and other rooms who have the v.token.   Can we have a FR that allows this ?

**Comment by daniel-sc** [comment]
Hi @thetuyo 

thanks for the feedback! 

I'm not sure I understand your other question - could you create a new issue for it and provide some more details on what you want to archive?

**Comment by thetuyo** [comment]
The request is to have a function that allows subscription to a LiveChat room messages, currently I think the only subscription is to a normal room (channel)

I will create a new issue.
