### ISSUE TITLE
Cannot login to Rocket.Chat server 4.2.2

### ISSUE THREAD

**Issue by tuxmartin** [daniel-sc/rocketchat-modern-client#27]
Hello,

after Rocket.Chat (snap) upgrade to the version 4.4.2 my application cannot connect to my rocket.chat server. Before that I had Rocket.Chat server 4.3.x. So I don't know if the bug is in the version 4.4.0, 4.4.1 or 4.4.2.

In the log I see only:
```
INFO  c.g.d.r.m.RocketChatClient:112 - connecting to wss://chat.examle.net:443/websocket
WARN  c.g.d.r.m.RocketChatClient:381 - connection closed: CloseReason: code [1006], reason [Unexpected Status of SSLEngineResult after an unwrap() operation]
```

I'm using latest maven version 1.3.1.

**Comment by daniel-sc** [comment]
@tuxmartin thanks for reporting this!
Are you sure you are using the correct url and ssl is setup correctly?

**Comment by tuxmartin** [comment]
@daniel-sc I haven't made any changes to my app in the last two months.

But I can't rule out any my mistake.

**Comment by tuxmartin** [comment]
@daniel-sc did you manage to simulate the same problem as me?

**Comment by daniel-sc** [comment]
Hi @tuxmartin, I looked into this and fixed some (probably) unrelated problem. With v1.3.2 I could successfully connect to `wss://open.rocket.chat:443/websocket`, which is running 4.5.0(-pre?). 
So it seems to me, that probably your ssl setup of the server is not correct. What setup do you have? [Auto SSL with snaps](https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/snaps/auto-ssl-with-snaps) or a [SSL reverse proxy](https://docs.rocket.chat/quick-start/installing-and-updating/other-deployment-methods/manual-installation/extras/configuring-ssl-reverse-proxy). Can you connect with the ordinary UI?

**Comment by tuxmartin** [comment]
@daniel-sc I have rocket.chat installed using snap + nginx (from apt) ssl proxy.

I tried `rocketchat-modern-client v1.3.2` and it works!

Thanks.
